version: '3'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    image: nemosanima/backend_api:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend


volumes:
  postgres_data:
    external: false
